### PR TITLE
[pulsar] Upgrade ingress api to `networking.k8s.io/v1`

### LINKED ISSUE #640: helm install failed: No kind ingress in version extensions/v1beta1
Streamnative pulsar helm chart installation failed in kubernetes v1.22+. 

Symptom:
➜  pulsar-helm-chart git:(master) ✗ helm install sn -n pulsar streamnative/pulsar --set initialize=true 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"

Kubernetes version:
➜  pulsar-helm-chart git:(master) ✗ k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

Ingress API
➜  pulsar-helm-chart git:(master) ✗ k api-resources|grep ingress
ingressclasses                                      networking.k8s.io/v1                   false        IngressClass
ingresses                         ing               networking.k8s.io/v1                   true         Ingress

Reason: this api is deprecated and unavailable in 1.22+
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

### PR DESCRIPTION
**Pull request by FushuWang**
Fixes #640 

### Motivation

Fix ingress api issue when installing pulsar chart into k8s v1.19+.

### Modifications

Breaking changes. 

Use `networking.k8s.io/v1` directly which requires the k8s version is v1.19+.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

Check the box below.

Need to update docs? 

  
- [x] `no-need-doc` 
  
  (Please explain why)

### CODE REVIEW

File: hack/common.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ OUTPUT_BIN=${OUTPUT}/bin
 KUBECTL_VERSION=1.14.3
 KUBECTL_BIN=$OUTPUT_BIN/kubectl
 HELM_BIN=$OUTPUT_BIN/helm
-HELM_VERSION=3.0.1
+HELM_VERSION=3.7.2
```
Comment (jdmaguire) [inline hack/common.sh:31]: Any particular reason for helm 3.7.2? The latest is 3.9.4.

**Review by jdmaguire — APPROVED** [review]

**Review by maxsxu — APPROVED** [review]

File: hack/common.sh (hunk 1 above)
Comment (FushuWang) [reply hack/common.sh:31]: > Any particular reason for helm 3.7.2? The latest is 3.9.4.

According to the [Helm Supported Versions](https://helm.sh/docs/topics/version_skew/#supported-version-skew), considering the compatibility we haven't tested this chart in the newer k8s version, so I choose 3.7.2. We can upgrade it later
